---
####script to launch docker-compose gvm  
- name: playbook
  hosts: all
  become: yes
  become_user: root
  tasks:


    - name: launch docker-compose gvm
      shell: docker-compose up -d
    - name: docker-compose-logs
      shell: docker-compose logs
      register: output
    - debug:
        var: output.stdout_lines
        verbosity: 2

